markdown: kramdown
kramdown:
  input: GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  hard_wrap: false

  extensions:
    - autolink
    - footnotes
    - smart
    - table
highlighter: rouge
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: justbio
author: "justbio"
email: justbio@163.com
name: "Bio's Notebook"
url: https://justbio.github.io/
domain: justbio.github.io
all_categories: [
["program", "python","/posts/program.html"],
["zabbix", "zabbix","/posts/zabbix.html"],
["linux", "Linux相关","/posts/linux.html"],
["read", "学习笔记","/posts/read.html"],
["github", "Github","/posts/github.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: Asia/Shanghai

collections:
  docs:
    output: true

gems:
 - jekyll-paginate

layout: default
comments: true
